red: missing item called has in cpp
/usr/bin/ld: /tmp/ccXO55wI.o: in function `CATCH2_INTERNAL_TEST_2()':
tests.cpp:(.text+0x459): undefined reference to `Inventory::has(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) const'
collect2: error: ld returned 1 exit status