red: removing a missing item is a no-op
read about tdd, need to update with red format accordingly

tests.cpp:(.text+0x62): undefined reference to `Inventory::add(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
/usr/bin/ld: tests.cpp:(.text+0x105): undefined reference to `Inventory::count() const'