red: missing remove, failed test 4
/usr/bin/ld: /tmp/cc68cSfP.o: in function `CATCH2_INTERNAL_TEST_4()':
tests.cpp:(.text+0x6c7): undefined reference to `Inventory::remove(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
collect2: error: ld returned 1 exit status