red: missing Inventory::count()
/usr/bin/ld: /tmp/cclfFcRA.o: in function `CATCH2_INTERNAL_TEST_0()':
tests.cpp:(.text+0x114): undefined reference to `Inventory::count() const'
collect2: error: ld returned 1 exit status